### PR TITLE
Bugheist to BLT-Flutter

### PR DESCRIPTION
**Pull request by just-ary27**
This PR starts a series of upcoming PRs whuch will migrate the BugHeist app to BLT under OWASP

### CODE REVIEW

**Comment by fredfalcon** [comment]
Thank you for starting this! I think plain BLT is a better name. The repo is here, can you please create the PR against that repo?

**Comment by just-ary27** [comment]
Do you want to keep the app and website in same repo?

**Comment by fredfalcon** [comment]
Not at the moment, when we transfer this to owasp we can call it BLT-Flutter or OWASP-BLT or BLT-app…

**Comment by just-ary27** [comment]
@fredfalcon changed the pr name, it required a review to merge

**Comment by fredfalcon** [comment]
Would you please do the pr to the BLT repo?  Id like to see the diff with the base code.

**Pull request closed without merging**
